### ISSUE TITLE
Frontend dashboard switches do not work in last version

### ISSUE THREAD

**Issue by SubToaD** [Koenkk/zigbee2mqtt#22028]
### What happened?

Hello,
Socket and bulb switches do not work in the frontend dashboard (they activate but no action, returns to the origin with a refresh), **but works in the expose state of each device**

### What did you expect to happen?

they worked in the previous version 1.36.0

### How to reproduce it (minimal and precise)

browser console

### Zigbee2MQTT version

1.36.1-dev commit: 5077b03

### Adapter firmware version

7.4.1 [GA]

### Adapter

SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

### Setup

RPi4 Debian11 Docker container

### Debug log

index-fb4a4614.js:40 Uncaught TypeError: a is not a function
    at onChange (Dashboard-cc086107.js:1:3112)
    at Yt.onChange (DashboardFeatureWrapper-ef543cb2.js:1:27283)
    at Yt.onChange (DashboardFeatureWrapper-ef543cb2.js:1:27283)
    at onChange (DashboardFeatureWrapper-ef543cb2.js:1:2373)
    at i (DashboardFeatureWrapper-ef543cb2.js:1:1405)
    at Object.xye (index-fb4a4614.js:40:9864)
    at Hye (index-fb4a4614.js:40:10021)
    at jye (index-fb4a4614.js:40:10081)
    at qC (index-fb4a4614.js:40:31567)
    at EH (index-fb4a4614.js:40:31985)
onChange @ Dashboard-cc086107.js:1
Yt.onChange @ DashboardFeatureWrapper-ef543cb2.js:1
Yt.onChange @ DashboardFeatureWrapper-ef543cb2.js:1
onChange @ DashboardFeatureWrapper-ef543cb2.js:1
i @ DashboardFeatureWrapper-ef543cb2.js:1
xye @ index-fb4a4614.js:40
Hye @ index-fb4a4614.js:40
jye @ index-fb4a4614.js:40
qC @ index-fb4a4614.js:40
EH @ index-fb4a4614.js:40
(anonyme) @ index-fb4a4614.js:40
Lw @ index-fb4a4614.js:43
JR @ index-fb4a4614.js:40
Hg @ index-fb4a4614.js:40
ow @ index-fb4a4614.js:40
eke @ index-fb4a4614.js:40

**Comment by ivanfrolovmd** [comment]
There's this error in console when switch is manually triggered:
```
Uncaught TypeError: a is not a function
    onChange http://smarthome.local:8080/assets/Dashboard-cc086107.js:1
    onChange http://smarthome.local:8080/assets/DashboardFeatureWrapper-ef543cb2.js:1
    onChange http://smarthome.local:8080/assets/DashboardFeatureWrapper-ef543cb2.js:1
    onChange http://smarthome.local:8080/assets/DashboardFeatureWrapper-ef543cb2.js:1
    i http://smarthome.local:8080/assets/DashboardFeatureWrapper-ef543cb2.js:1
    xye http://smarthome.local:8080/assets/index-fb4a4614.js:40
    Hye http://smarthome.local:8080/assets/index-fb4a4614.js:40
    jye http://smarthome.local:8080/assets/index-fb4a4614.js:40
    qC http://smarthome.local:8080/assets/index-fb4a4614.js:40
    EH http://smarthome.local:8080/assets/index-fb4a4614.js:40
    Hg http://smarthome.local:8080/assets/index-fb4a4614.js:40
    Lw http://smarthome.local:8080/assets/index-fb4a4614.js:43
    JR http://smarthome.local:8080/assets/index-fb4a4614.js:40
    Hg http://smarthome.local:8080/assets/index-fb4a4614.js:40
    ow http://smarthome.local:8080/assets/index-fb4a4614.js:40
    eke http://smarthome.local:8080/assets/index-fb4a4614.js:40
    DH http://smarthome.local:8080/assets/index-fb4a4614.js:40
    Rg http://smarthome.local:8080/assets/index-fb4a4614.js:40
    l http://smarthome.local:8080/assets/index-fb4a4614.js:40
    $l http://smarthome.local:8080/assets/index-fb4a4614.js:40
    createRoot http://smarthome.local:8080/assets/index-fb4a4614.js:43
    <anonymous> http://smarthome.local:8080/assets/index-fb4a4614.js:217
Dashboard-cc086107.js:1:3113
```

**Comment by cracyfloyd** [comment]
Here the same.
with Conbee 3 and Debian 12 VM on MacMini (zigbee2mqtt Docker).
