### ISSUE TITLE
No logs in HA addon

### ISSUE THREAD

**Issue by pilot1981** [Koenkk/zigbee2mqtt#24791]
### What happened?

No logs in HA ADDON:

Failed to get 45df7312_zigbee2mqtt logs, e.callApiRaw is not a function. (In 'e.callApiRaw("GET",`hassio/${t.includes("_")?`addons/${t}`:t}/logs${0!==r?`/boots/${r}`:""}`,void 0,i?{Range:i}:void 0)', 'e.callApiRaw' is undefined)

### What did you expect to happen?

I expect to see logs in HA ADDON section.

I can confirm download logs from ADDON Zigbee2MQTT section of HA works fine

I can confirm I can see logs from general section of logs of HA (seelct Zigbee2MQTT on top right) works fine

### How to reproduce it (minimal and precise)

Boot HA without USB coordinator

### Zigbee2MQTT version

1.41.0-1

### Adapter firmware version

Zigbee (EZSP) [7.4.3.0](http://7.4.3.0/) build 0
https://github.com/darkxst/silabs-firmware-builder/blob/main/firmware_builds/zbdonglee/ncp-uart-hw-v7.4.3.0-zbdonglee-115200.gbl

### Home Assistant OS version

2024.10.4

### Adapter

SONOFF ZBDONGLE-E 3.0 USB

### Setup

Home assistant OS on VM on QNAP, Sonoff ZbDongle-3 e.0 connected to USB port of QNAP, Addon Zigbee2MQTT installed on HA

### Debug log

Failed to get 45df7312_zigbee2mqtt logs, e.callApiRaw is not a function. (In 'e.callApiRaw("GET",`hassio/${t.includes("_")?`addons/${t}`:t}/logs${0!==r?`/boots/${r}`:""}`,void 0,i?{Range:i}:void 0)', 'e.callApiRaw' is undefined)

<img width="1235" alt="Schermata 2024-11-16 alle 19 51 32" src="https://github.com/user-attachments/assets/927f6f29-1950-4eed-9334-b425f950ca5e">

**Comment by Ricc68** [comment]
Same issue as #24694 and #24785.

**Comment by Suffice** [comment]
Happened to me after I added a new device. Was working fine earlier today.

**Comment by Nerivec** [comment]
This is not limited to Z2M addon and is a problem on HA side. Should be fixed after updating supervisor to [2024.11.3](https://github.com/home-assistant/supervisor/releases/tag/2024.11.3) or later.

**Comment by pilot1981** [comment]
it started again working after updated HA to 2024.11.2 version...
