### ISSUE TITLE
Xiaomi Miio and all dependencies are failing to load 

### ISSUE THREAD

**Issue by Zafrirshha** [Koenkk/zigbee2mqtt#30071]
### What happened?

After upgrade to MQTT to 2.7.1-1, Xiaomi Miio and all its dependencies (Viomi vacuum & Xiaomi Map extrator) fail to load with the error - Setup failed for 'xiaomi_miio': Unable to import component: cannot import name 'ROCKROBO_S7_MAXV' from 'miio.integrations.vacuum.roborock.vacuum' (/usr/local/lib/python3.13/site-packages/miio/integrations/vacuum/roborock/vacuum.py)

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/loader.py", line 1018, in async_get_component

    comp = await self.hass.async_add_import_executor_job(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        self._get_component, True

        ^^^^^^^^^^^^^^^^^^^^^^^^^

    )

    ^

  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component

    ComponentProtocol, importlib.import_module(self.pkg_path)

                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module

  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed

  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 44, in <module>

    from .const import (

    ...<28 lines>...

    )

  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/const.py", line 3, in <module>

    from miio.integrations.vacuum.roborock.vacuum import (

    ...<11 lines>...

    )

ImportError: cannot import name 'ROCKROBO_S7_MAXV' from 'miio.integrations.vacuum.roborock.vacuum' (/usr/local/lib/python3.13/site-packages/miio/integrations/vacuum/roborock/vacuum.py)



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component

    component = await integration.async_get_component()

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/loader.py", line 1038, in async_get_component

    self._component_future.result()

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^

  File "/usr/src/homeassistant/homeassistant/loader.py", line 1030, in async_get_component

    comp = self._get_component()

  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component

    ComponentProtocol, importlib.import_module(self.pkg_path)

                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module

  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed

  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 44, in <module>

    from .const import (

    ...<28 lines>...

    )

  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/const.py", line 3, in <module>

    from miio.integrations.vacuum.roborock.vacuum import (

    ...<11 lines>...

    )

ImportError: cannot import name 'ROCKROBO_S7_MAXV' from 'miio.integrations.vacuum.roborock.vacuum' (/usr/local/lib/python3.13/site-packages/miio/integrations/vacuum/roborock/vacuum.py)

### What did you expect to happen?

_No response_

### How to reproduce it (minimal and precise)

_No response_

### Zigbee2MQTT version

1.2.1-1

### Adapter firmware version

20251203.1

### Adapter

Sonoff Zigbee

### Setup

Home Assistant OS 2025.12.1

### Device `database.db` entry

_No response_

### Debug log

_No response_

### Notes

_No response_

**Comment by Zafrirshha** [comment]
After restoring to previous MQTT version (backup from the last upgrade) all Xiaomi & Viomi return to normal work

**Comment by Koenkk** [comment]
Z2M is not related to the `xiaomi_miio` component, please create an issue for the `xiaomi_miio` component.
