### ISSUE TITLE
Error after updating to 1.23.0-dev commit #1eb32870

### ISSUE THREAD

**Issue by SargonofAssyria** [Koenkk/zigbee2mqtt#11675]
### What happened?

Error is frequently present.
`error 2022-03-02 15:21:27: Exception while calling fromZigbee converter: fz.battery is not a function}`
the error is still present when I updated today to 1.24.0-dev commit #3535b2c6
It seems related to device: https://www.zigbee2mqtt.io/devices/TS0201.html#tuya-ts0201
Might be related to https://github.com/Koenkk/zigbee2mqtt/issues/11470
When I change line 669 back to the previous my error is gone.

### What did you expect to happen?

No error as before.

### Zigbee2MQTT version

1.24.0-dev

### Adapter firmware version

20220103

### Adapter

Texas Instruments LAUNCHXL-CC1352P-2

**Comment by Koenkk** [comment]
should be fixed now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by SargonofAssyria** [comment]
Tnx, That works, no more errors....
