### ISSUE TITLE
Zigbee2MQTT doesn't start after upgrade to 2.6.3

### ISSUE THREAD

**Issue by FrankGiesecke** [Koenkk/zigbee2mqtt#29506]
### What happened?

I'm using z2m installed on Linux.

After Upgrading from 2.6.2 to 2.6.3, z2m failed to start.

```
Nov 07 10:29:32 zigbee2mqtt-kg node[47368]: Starting Zigbee2MQTT without watchdog.
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]: Error: Cannot find module 'moment'
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]: Require stack:
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]: - /opt/zigbee2mqtt/dist/util/logger.js
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]: - /opt/zigbee2mqtt/dist/eventBus.js
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]: - /opt/zigbee2mqtt/dist/controller.js
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]: - /opt/zigbee2mqtt/index.js
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]:     at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]:     at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]:     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]:     at Function._load (node:internal/modules/cjs/loader:1192:37)
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]:     at TracingChannel.traceSync (node:diagnostics_channel:328:14)
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]:     at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]:     at Module.require (node:internal/modules/cjs/loader:1463:12)
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]:     at require (node:internal/modules/helpers:147:16)
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]:     at Object.<anonymous> (/opt/zigbee2mqtt/lib/util/logger.ts:5:1)
Nov 07 10:29:33 zigbee2mqtt-kg node[47368]:     at Module._compile (node:internal/modules/cjs/loader:1706:14)
Nov 07 10:29:33 zigbee2mqtt-kg systemd[1]: zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
```

Why is the module 'moment' missing.
I couldn't find any reference in the package.json or pnpm-lock.yaml

### What did you expect to happen?

All required modules will be installed.

### Zigbee2MQTT version

2.6.3

### Adapter firmware version

-

### Adapter

-

### Setup

Installed on Linux using Ansible and the Role https://github.com/final-gene/ansible-role-zigbee2mqtt

```
Linux zigbee2mqtt-kg 6.8.12-15-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-15 (2025-09-12T11:02Z) x86_64 GNU/Linux
Debian GNU/Linux 12
```

**Comment by FrankGiesecke** [comment]
The problem is solveld.

Further investigation has shown an error during the upgrade.
```
root@zigbee2mqtt-out:/opt/zigbee2mqtt# pnpm run build

> zigbee2mqtt@2.6.3 build /opt/zigbee2mqtt
> tsc && node index.js writehash


<--- Last few GCs --->

[269:0xd9c6000]    22248 ms: Mark-Compact 251.2 (258.6) -> 250.0 (258.8) MB, pooled: 0 MB, 288.46 / 0.00 ms  (average mu = 0.079, current mu = 0.056) allocation failure; scavenge might not succeed
[269:0xd9c6000]    22562 ms: Mark-Compact 251.1 (258.8) -> 250.1 (258.3) MB, pooled: 1 MB, 311.77 / 0.00 ms  (average mu = 0.042, current mu = 0.006) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xe38a0e node::OOMErrorHandler(char const*, v8::OOMDetails const&) [node]
 2: 0x120a5a0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 3: 0x120a877 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 4: 0x1438155  [node]
 5: 0x1438183  [node]
 6: 0x145125a  [node]
 7: 0x1454428  [node]
 8: 0x1cba291  [node]
Aborted
 ELIFECYCLE  Command failed with exit code 134.
```

# REASON
The underlying LXC container has to less memory.  
Zigbee2MQTT runs fine with just 256MB RAM. But the PNPM Process needs much more.  
The process finished successful after increasing the memory to 1024MB.
