### ISSUE TITLE
Errormessages after update to 1.26.0

### ISSUE THREAD

**Issue by reinhardsiegel79** [Koenkk/zigbee2mqtt#13010]
### What happened?

After Update of zigbee2mqtt home assistant addon the logfile is swamped with following errors:

> zigbee2mqtt@1.26.0 start
> node index.js
/app/dist/util/externally-loaded.js:178
            .withRunningState(['idle', 'heat'], ea.STATE).withAwayMode()],
                                                          ^
TypeError: exposes.climate(...).withSetpoint(...).withLocalTemperature(...).withSystemMode(...).withLocalTemperatureCalibration(...).withRunningState(...).withAwayMode is not a function
    at /app/dist/util/externally-loaded.js:178:59
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)
    at Object.runInNewContext (node:vm:298:38)
    at loadModuleFromText (/app/lib/util/utils.ts:148:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:155:12)
    at Object.getExternalConvertersDefinitions (/app/lib/util/utils.ts:165:25)
    at getExternalConvertersDefinitions.next (<anonymous>)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:12:20)
    at new Controller (/app/lib/controller.ts:84:58)

This prevents Zigbee2Mqtt start and work. I can go back to a previous version for now though.

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

0x26680700

### Adapter

ConBee2/RaspBee2

**Comment by Koenkk** [comment]
`withAwayMode()` has been removed, you should update your external converter. Example: https://github.com/Koenkk/zigbee-herdsman-converters/commit/73566d9dadfb280e56f70a711a40561ade47dbc8
