### ISSUE TITLE
Error with Domoticz

### ISSUE THREAD

**Issue by cndian** [Koenkk/zigbee2mqtt#7588]
Hello,

After updating the Domoticz Zigbee plugin to 3.0.0. I constant get this error;

`2021-05-24 22:50:34.719 Error: Zigbee2mqtt: (Zigbee2mqtt) 'onMessage' failed 'TypeError':'remove() missing 1 required positional argument: 'ieee_addr''. 
2021-05-24 22:50:34.719 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 297 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage 
2021-05-24 22:50:34.719 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 137 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage 
2021-05-24 22:50:34.720 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage 
2021-05-24 22:50:34.720 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 155 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish 
2021-05-24 22:50:34.720 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 37 in '/home/pi/domoticz/plugins/zigbee2mqtt/api/api.py', function handle_mqtt_message 
2021-05-24 22:50:34.720 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 53 in '/home/pi/domoticz/plugins/zigbee2mqtt/api/devices.py', function handle_mqtt_message 
2021-05-24 22:50:34.720 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 47 in '/home/pi/domoticz/plugins/zigbee2mqtt/api/api.py', function _handle_api_command 
2021-05-24 22:50:34.720 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 117 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onApiCommand 
2021-05-24 22:50:34.720 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 83 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py', function remove 

 2021-05-24 23:52:18.186 Error: Zigbee2mqtt: (Zigbee2mqtt) 'onMessage' failed 'KeyError'.
2021-05-24 23:52:18.186 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 297 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2021-05-24 23:52:18.186 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 137 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2021-05-24 23:52:18.186 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2021-05-24 23:52:18.186 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 219 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2021-05-24 23:52:18.186 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 81 in '/home/pi/domoticz/plugins/zigbee2mqtt/groups_manager.py', function handle_mqtt_message
2021-05-24 23:52:18.186 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 64 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py', function handle_mqtt_message
2021-05-24 23:52:18.186 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 65 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/base_colortemp_light.py', function handle_message
2021-05-24 23:52:18.186 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 22 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/base_colortemp_light.py', function 

Also my temp sensors in Domoticz shows for example 3000volts, before the update it was 3.000 volt. Also I can't remove device with the Zigbee plugin.

How can I resolve this?
