### ISSUE TITLE
zigbee2mqtt fails to start after update to 1.35.2

### ISSUE THREAD

**Issue by igor-semenov** [Koenkk/zigbee2mqtt#21161]
### What happened?

I updated zigbee2mqtt via update.sh, after that service fails with
```
фев 02 14:11:58 raspberrypi systemd[1]: Started zigbee2mqtt.
фев 02 14:11:58 raspberrypi bash[18356]: > zigbee2mqtt@1.35.2 start /opt/zigbee2mqtt
фев 02 14:11:58 raspberrypi bash[18356]: > node index.js
фев 02 14:11:59 raspberrypi bash[18356]: Building Zigbee2MQTT... (initial build)(node:18370) UnhandledPromiseRejectionWarning: TypeError: rimrafSync is not a function
фев 02 14:11:59 raspberrypi bash[18356]:     at Promise (/opt/zigbee2mqtt/index.js:44:9)
фев 02 14:11:59 raspberrypi bash[18356]:     at new Promise (<anonymous>)
фев 02 14:11:59 raspberrypi bash[18356]:     at build (/opt/zigbee2mqtt/index.js:42:12)
фев 02 14:11:59 raspberrypi bash[18356]:     at checkDist (/opt/zigbee2mqtt/index.js:71:15)
фев 02 14:11:59 raspberrypi bash[18356]:     at start (/opt/zigbee2mqtt/index.js:82:11)
фев 02 14:11:59 raspberrypi bash[18356]:     at Object.<anonymous> (/opt/zigbee2mqtt/index.js:127:9)
фев 02 14:11:59 raspberrypi bash[18356]:     at Module._compile (internal/modules/cjs/loader.js:689:30)
фев 02 14:11:59 raspberrypi bash[18356]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
фев 02 14:11:59 raspberrypi bash[18356]:     at Module.load (internal/modules/cjs/loader.js:599:32)
фев 02 14:11:59 raspberrypi bash[18356]:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
фев 02 14:11:59 raspberrypi bash[18356]: (node:18370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a
фев 02 14:11:59 raspberrypi bash[18356]: (node:18370) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will termin
фев 02 14:11:59 raspberrypi systemd[1]: zigbee2mqtt.service: Succeeded.
фев 02 14:11:59 raspberrypi systemd[1]: zigbee2mqtt.service: Service RestartSec=100ms expired, scheduling restart.
фев 02 14:11:59 raspberrypi systemd[1]: zigbee2mqtt.service: Scheduled restart job, restart counter is at 5.
фев 02 14:11:59 raspberrypi systemd[1]: Stopped zigbee2mqtt.
фев 02 14:11:59 raspberrypi systemd[1]: zigbee2mqtt.service: Start request repeated too quickly.
фев 02 14:11:59 raspberrypi systemd[1]: zigbee2mqtt.service: Failed with result 'start-limit-hit'.
фев 02 14:11:59 raspberrypi systemd[1]: Failed to start zigbee2mqtt.
```

### What did you expect to happen?

Service work as before update.

### Zigbee2MQTT version

1.35.2

### Adapter firmware version

?

### Adapter

*

### Setup

Home Assistant on Raspberry PI

**Comment by igor-semenov** [comment]
I tried to update nodejs in python venv, updated to 18.19.0, but now npm is not working in venv:
```
$ npm --version
/opt/zigbee2mqtt/lib/node_modules/npm/lib/es6/validate-engines.js:31
    throw err
    ^

TypeError: LRU is not a constructor
    at Object.<anonymous> (/opt/zigbee2mqtt/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modules/make-fetch-happen/agent.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/opt/zigbee2mqtt/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modules/make-fetch-happen/index.js:11:18)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)

Node.js v18.19.0
```

**Comment by igor-semenov** [comment]
With 16.15.0 also not working:
```
$ npm --version
TypeError: Class extends value #<Object> is not a constructor or null
    at Object.<anonymous> (/opt/zigbee2mqtt/lib/node_modules/npm/node_modules/tar/lib/read-entry.js:91:4)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/zigbee2mqtt/lib/node_modules/npm/node_modules/tar/lib/pack.js:27:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```

**Comment by igor-semenov** [comment]
I managed to fix npm: removed `lib/node_modules`, reinstalled all from scratch.
BTW I used nodejs 18.19.0, while 16.15.0 is recommended (https://www.zigbee2mqtt.io/guide/installation/07_python_virtual_environment.html#installing)
